// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeknikServisApp.Infrastructure.Data;

#nullable disable

namespace TeknikServisApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260123080206_InitialMigration2")]
    partial class InitialMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Bayi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Il")
                        .HasColumnType("text");

                    b.Property<string>("Ilce")
                        .HasColumnType("text");

                    b.Property<string>("Kod")
                        .HasColumnType("text");

                    b.Property<bool>("MerkezMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("YetkiliAd")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Bayiler");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Depo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BayiId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kod")
                        .HasColumnType("text");

                    b.Property<bool>("MerkezDepoMu")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BayiId");

                    b.HasIndex("TenantId");

                    b.ToTable("Depolar");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Fatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AraToplam")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BayiId")
                        .HasColumnType("uuid");

                    b.Property<string>("FaturaNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FaturaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GenelToplam")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("IndirimTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IptalEdildi")
                        .HasColumnType("boolean");

                    b.Property<string>("IptalNedeni")
                        .HasColumnType("text");

                    b.Property<decimal>("KdvToplam")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MusteriAd")
                        .HasColumnType("text");

                    b.Property<string>("MusteriAdres")
                        .HasColumnType("text");

                    b.Property<Guid?>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("MusteriVergiNo")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Onaylandi")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SatisId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("TeknikServisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BayiId");

                    b.HasIndex("FaturaNo")
                        .IsUnique();

                    b.HasIndex("MusteriId");

                    b.HasIndex("SatisId");

                    b.HasIndex("TeknikServisId");

                    b.HasIndex("TenantId");

                    b.ToTable("Faturalar");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.FaturaKalem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<decimal>("BirimFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("FaturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("IndirimTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("KdvOran")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("KdvTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Toplam")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("UrunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FaturaId");

                    b.HasIndex("UrunId");

                    b.ToTable("FaturaKalemleri");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Iade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BayiId")
                        .HasColumnType("uuid");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("IadeEdilen")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("IadeNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IadeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IslemYapanId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("Neden")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RedNedeni")
                        .HasColumnType("text");

                    b.Property<Guid>("SatisId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ToplamTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BayiId");

                    b.HasIndex("IslemYapanId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("SatisId");

                    b.HasIndex("TenantId");

                    b.ToTable("Iadeler");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.IadeKalem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IadeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("IadeTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Neden")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SatisKalemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeriNumarasiId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IadeId");

                    b.HasIndex("SatisKalemId");

                    b.HasIndex("SeriNumarasiId");

                    b.ToTable("IadeKalemleri");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Kasa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Bakiye")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BayiId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BayiId");

                    b.HasIndex("TenantId");

                    b.ToTable("Kasalar");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.KasaHareket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<Guid>("BayiId")
                        .HasColumnType("uuid");

                    b.Property<string>("BelgeNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KasaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OlusturanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OncekiBakiye")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<decimal>("SonrakiBakiye")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BayiId");

                    b.HasIndex("KasaId");

                    b.HasIndex("OlusturanId");

                    b.HasIndex("TenantId");

                    b.ToTable("KasaHareketleri");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Kategori", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kod")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UstKategoriId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UstKategoriId");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("BayiId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IseBaslamaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Maas")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenSonKullanma")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("YillikIzinHakki")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BayiId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Musteri", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<Guid?>("BayiId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Kurumsal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TcNo")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("VergiNo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BayiId");

                    b.HasIndex("TenantId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.PersonelAvans", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MaastanKesildiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OdendiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OnaylandiMi")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OnaylayanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonelId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OnaylayanId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("TenantId");

                    b.ToTable("PersonelAvanslari");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.PersonelIzin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<int>("GunSayisi")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IzinTipi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OnaylayanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonelId")
                        .HasColumnType("uuid");

                    b.Property<string>("RedNedeni")
                        .HasColumnType("text");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("UcretliMi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OnaylayanId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("TenantId");

                    b.ToTable("PersonelIzinleri");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.PersonelMaasOdeme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvansKesinti")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Ay")
                        .HasColumnType("integer");

                    b.Property<decimal>("BrutMaas")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("EkMesaiUcreti")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Kesinti")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("NetMaas")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("OdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OdendiMi")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OdeyenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PersonelId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ToplamOdeme")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Yil")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OdeyenId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("TenantId");

                    b.ToTable("PersonelMaasOdemeleri");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.PersonelMesai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OnaylandiMi")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OnaylayanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonelId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SaatUcreti")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ToplamSaat")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ToplamUcret")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OnaylayanId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("TenantId");

                    b.ToTable("PersonelMesaileri");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Satis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<decimal>("AraToplam")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BayiId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("GenelToplam")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("IndirimTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IptalEdildi")
                        .HasColumnType("boolean");

                    b.Property<string>("IptalNedeni")
                        .HasColumnType("text");

                    b.Property<DateTime?>("IptalTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("KartTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("KdvToplam")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MusteriAd")
                        .HasColumnType("text");

                    b.Property<Guid?>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("MusteriTelefon")
                        .HasColumnType("text");

                    b.Property<decimal>("NakitTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("OdemeTipi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SatisNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SatisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SatisYapanId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BayiId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("SatisNo")
                        .IsUnique();

                    b.HasIndex("SatisYapanId");

                    b.HasIndex("TenantId");

                    b.ToTable("Satislar");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.SatisKalem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BirimFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("IndirimTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("KdvOran")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("KdvTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SatisId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeriNumarasiId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Toplam")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("UrunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SatisId");

                    b.HasIndex("SeriNumarasiId");

                    b.HasIndex("UrunId");

                    b.ToTable("SatisKalemleri");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Sayim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BaslatanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BayiId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<int>("Fark")
                        .HasColumnType("integer");

                    b.Property<int>("FizikselStok")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SayimNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<int>("SistemStok")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BaslatanId");

                    b.HasIndex("BayiId");

                    b.HasIndex("DepoId");

                    b.HasIndex("TenantId");

                    b.ToTable("Sayimlar");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.SayimKalem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("FizikiSayimda")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SayimId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeriNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SeriNumarasiId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<bool>("SistemdeVar")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TaramaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UrunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SayimId");

                    b.HasIndex("SeriNumarasiId");

                    b.HasIndex("UrunId");

                    b.ToTable("SayimKalemleri");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.SeriNumarasi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<decimal?>("AlisFiyati")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("BayiId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Satildi")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("SatisFiyati")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("SatisId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SatisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeriNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UrunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BayiId");

                    b.HasIndex("DepoId");

                    b.HasIndex("SeriNo");

                    b.HasIndex("TenantId");

                    b.HasIndex("UrunId");

                    b.ToTable("SeriNumaralari");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.StokHareket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<Guid>("BayiId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SeriNumarasiId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.Property<Guid>("UrunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BayiId");

                    b.HasIndex("DepoId");

                    b.HasIndex("SeriNumarasiId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UrunId");

                    b.ToTable("StokHareketleri");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.TeknikServisKalem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BirimFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParcaAdi")
                        .HasColumnType("text");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TeknikServisId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Toplam")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("UrunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeknikServisId");

                    b.HasIndex("UrunId");

                    b.ToTable("TeknikServisKalemleri");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.TeknikServisKayit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ariza")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArizaDetay")
                        .HasColumnType("text");

                    b.Property<Guid>("BayiId")
                        .HasColumnType("uuid");

                    b.Property<string>("CihazMarka")
                        .HasColumnType("text");

                    b.Property<string>("CihazModel")
                        .HasColumnType("text");

                    b.Property<string>("CihazSifre")
                        .HasColumnType("text");

                    b.Property<string>("CihazTip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<bool>("GarantiKapsami")
                        .HasColumnType("boolean");

                    b.Property<string>("GarantiNot")
                        .HasColumnType("text");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImeiNo")
                        .HasColumnType("text");

                    b.Property<string>("IptalNedeni")
                        .HasColumnType("text");

                    b.Property<decimal>("IscilikUcreti")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MusteriAd")
                        .HasColumnType("text");

                    b.Property<Guid?>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("MusteriTelefon")
                        .HasColumnType("text");

                    b.Property<bool>("OdemeAlindi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OdenenTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ParcaToplam")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("SeriNo")
                        .HasColumnType("text");

                    b.Property<string>("ServisNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SorumluPersonelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TahminiTeslimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TeslimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TespitNotlari")
                        .HasColumnType("text");

                    b.Property<decimal>("ToplamTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("YapilanIslem")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BayiId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("ServisNo")
                        .IsUnique();

                    b.HasIndex("SorumluPersonelId");

                    b.HasIndex("TenantId");

                    b.ToTable("TeknikServisler");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kod")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LisansBitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<string>("VergiNo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HedefDepoId")
                        .HasColumnType("uuid");

                    b.Property<string>("IptalNedeni")
                        .HasColumnType("text");

                    b.Property<Guid>("KaynakDepoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OlusturanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransferNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransferTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HedefDepoId");

                    b.HasIndex("KaynakDepoId");

                    b.HasIndex("OlusturanId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TransferNo")
                        .IsUnique();

                    b.ToTable("Transferler");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.TransferKalem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SeriNumarasiId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<bool>("TeslimAlindi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("TeslimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UrunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeriNumarasiId");

                    b.HasIndex("TransferId");

                    b.HasIndex("UrunId");

                    b.ToTable("TransferKalemleri");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Urun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<decimal>("AlisFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Barkod")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KategoriId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("KdvOran")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Kod")
                        .HasColumnType("text");

                    b.Property<int>("KritikStok")
                        .HasColumnType("integer");

                    b.Property<string>("Marka")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SatisFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("SeriTakipli")
                        .HasColumnType("boolean");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Barkod");

                    b.HasIndex("KategoriId");

                    b.HasIndex("TenantId");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Bayi", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Bayiler")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Depo", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Bayi", "Bayi")
                        .WithMany("Depolar")
                        .HasForeignKey("BayiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bayi");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Fatura", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Bayi", "Bayi")
                        .WithMany()
                        .HasForeignKey("BayiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Satis", "Satis")
                        .WithMany()
                        .HasForeignKey("SatisId");

                    b.HasOne("TeknikServisApp.Domain.Entities.TeknikServisKayit", "TeknikServis")
                        .WithMany()
                        .HasForeignKey("TeknikServisId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bayi");

                    b.Navigation("Musteri");

                    b.Navigation("Satis");

                    b.Navigation("TeknikServis");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.FaturaKalem", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Fatura", "Fatura")
                        .WithMany("Kalemler")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId");

                    b.Navigation("Fatura");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Iade", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Bayi", "Bayi")
                        .WithMany()
                        .HasForeignKey("BayiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Kullanici", "IslemYapan")
                        .WithMany()
                        .HasForeignKey("IslemYapanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Satis", "Satis")
                        .WithMany()
                        .HasForeignKey("SatisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bayi");

                    b.Navigation("IslemYapan");

                    b.Navigation("Musteri");

                    b.Navigation("Satis");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.IadeKalem", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Iade", "Iade")
                        .WithMany("Kalemler")
                        .HasForeignKey("IadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.SatisKalem", "SatisKalem")
                        .WithMany()
                        .HasForeignKey("SatisKalemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.SeriNumarasi", "SeriNumarasi")
                        .WithMany()
                        .HasForeignKey("SeriNumarasiId");

                    b.Navigation("Iade");

                    b.Navigation("SatisKalem");

                    b.Navigation("SeriNumarasi");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Kasa", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Bayi", "Bayi")
                        .WithMany("Kasalar")
                        .HasForeignKey("BayiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bayi");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.KasaHareket", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Bayi", "Bayi")
                        .WithMany()
                        .HasForeignKey("BayiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Kasa", "Kasa")
                        .WithMany("Hareketler")
                        .HasForeignKey("KasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Kullanici", "Olusturan")
                        .WithMany()
                        .HasForeignKey("OlusturanId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bayi");

                    b.Navigation("Kasa");

                    b.Navigation("Olusturan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Kategori", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Kategori", "UstKategori")
                        .WithMany("AltKategoriler")
                        .HasForeignKey("UstKategoriId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tenant");

                    b.Navigation("UstKategori");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Kullanici", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Bayi", "Bayi")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("BayiId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bayi");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Musteri", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Bayi", "Bayi")
                        .WithMany()
                        .HasForeignKey("BayiId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bayi");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.PersonelAvans", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Kullanici", "Onaylayan")
                        .WithMany()
                        .HasForeignKey("OnaylayanId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Kullanici", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Onaylayan");

                    b.Navigation("Personel");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.PersonelIzin", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Kullanici", "Onaylayan")
                        .WithMany()
                        .HasForeignKey("OnaylayanId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Kullanici", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Onaylayan");

                    b.Navigation("Personel");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.PersonelMaasOdeme", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Kullanici", "Odeyen")
                        .WithMany()
                        .HasForeignKey("OdeyenId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Kullanici", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Odeyen");

                    b.Navigation("Personel");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.PersonelMesai", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Kullanici", "Onaylayan")
                        .WithMany()
                        .HasForeignKey("OnaylayanId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Kullanici", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Onaylayan");

                    b.Navigation("Personel");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Satis", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Bayi", "Bayi")
                        .WithMany()
                        .HasForeignKey("BayiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Kullanici", "SatisYapan")
                        .WithMany()
                        .HasForeignKey("SatisYapanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bayi");

                    b.Navigation("Musteri");

                    b.Navigation("SatisYapan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.SatisKalem", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Satis", "Satis")
                        .WithMany("Kalemler")
                        .HasForeignKey("SatisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.SeriNumarasi", "SeriNumarasi")
                        .WithMany()
                        .HasForeignKey("SeriNumarasiId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Satis");

                    b.Navigation("SeriNumarasi");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Sayim", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Kullanici", "Baslatan")
                        .WithMany()
                        .HasForeignKey("BaslatanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Bayi", "Bayi")
                        .WithMany()
                        .HasForeignKey("BayiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Depo", "Depo")
                        .WithMany()
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Baslatan");

                    b.Navigation("Bayi");

                    b.Navigation("Depo");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.SayimKalem", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Sayim", "Sayim")
                        .WithMany("Kalemler")
                        .HasForeignKey("SayimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.SeriNumarasi", "SeriNumarasi")
                        .WithMany()
                        .HasForeignKey("SeriNumarasiId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sayim");

                    b.Navigation("SeriNumarasi");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.SeriNumarasi", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Bayi", "Bayi")
                        .WithMany()
                        .HasForeignKey("BayiId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Depo", "Depo")
                        .WithMany("SeriNumaralari")
                        .HasForeignKey("DepoId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Urun", "Urun")
                        .WithMany("SeriNumaralari")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bayi");

                    b.Navigation("Depo");

                    b.Navigation("Tenant");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.StokHareket", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Bayi", "Bayi")
                        .WithMany()
                        .HasForeignKey("BayiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Depo", "Depo")
                        .WithMany()
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.SeriNumarasi", "SeriNumarasi")
                        .WithMany()
                        .HasForeignKey("SeriNumarasiId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bayi");

                    b.Navigation("Depo");

                    b.Navigation("SeriNumarasi");

                    b.Navigation("Tenant");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.TeknikServisKalem", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.TeknikServisKayit", "TeknikServis")
                        .WithMany("Kalemler")
                        .HasForeignKey("TeknikServisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId");

                    b.Navigation("TeknikServis");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.TeknikServisKayit", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Bayi", "Bayi")
                        .WithMany()
                        .HasForeignKey("BayiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Kullanici", "SorumluPersonel")
                        .WithMany()
                        .HasForeignKey("SorumluPersonelId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bayi");

                    b.Navigation("Musteri");

                    b.Navigation("SorumluPersonel");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Transfer", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Depo", "HedefDepo")
                        .WithMany()
                        .HasForeignKey("HedefDepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Depo", "KaynakDepo")
                        .WithMany()
                        .HasForeignKey("KaynakDepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Kullanici", "Olusturan")
                        .WithMany()
                        .HasForeignKey("OlusturanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HedefDepo");

                    b.Navigation("KaynakDepo");

                    b.Navigation("Olusturan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.TransferKalem", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.SeriNumarasi", "SeriNumarasi")
                        .WithMany()
                        .HasForeignKey("SeriNumarasiId");

                    b.HasOne("TeknikServisApp.Domain.Entities.Transfer", "Transfer")
                        .WithMany("Kalemler")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeriNumarasi");

                    b.Navigation("Transfer");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Urun", b =>
                {
                    b.HasOne("TeknikServisApp.Domain.Entities.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeknikServisApp.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Bayi", b =>
                {
                    b.Navigation("Depolar");

                    b.Navigation("Kasalar");

                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Depo", b =>
                {
                    b.Navigation("SeriNumaralari");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Fatura", b =>
                {
                    b.Navigation("Kalemler");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Iade", b =>
                {
                    b.Navigation("Kalemler");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Kasa", b =>
                {
                    b.Navigation("Hareketler");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Kategori", b =>
                {
                    b.Navigation("AltKategoriler");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Satis", b =>
                {
                    b.Navigation("Kalemler");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Sayim", b =>
                {
                    b.Navigation("Kalemler");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.TeknikServisKayit", b =>
                {
                    b.Navigation("Kalemler");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Bayiler");

                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Transfer", b =>
                {
                    b.Navigation("Kalemler");
                });

            modelBuilder.Entity("TeknikServisApp.Domain.Entities.Urun", b =>
                {
                    b.Navigation("SeriNumaralari");
                });
#pragma warning restore 612, 618
        }
    }
}
